server:
  port: 8001

spring:
  datasource:
    url: "jdbc:mysql://rm-bp16fv021jtaeyb5sfm.mysql.rds.aliyuncs.com/test_data\
                 ?useSSL=false&characterEncoding=utf-8&useUnicode=true&useSSL=false\
                 &allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai"
    username: root
    password: 'root'
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #连接池配置(通常来说，只需要修改initialSize、minIdle、maxActive
      initial-size: 1
      max-active: 20
      min-idle: 1
      # 配置获取连接等待超时的时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true